version: "3"
tasks:
  default:
    desc: タスク一覧を表示
    cmds:
      - task -l

  dev:
    desc: エミュレーターでアプリ実行（ホットリロード対応）
    dir: app
    cmds:
      # 環境変数設定
      - export ANDROID_ADB_SERVER_HOST=${ANDROID_ADB_SERVER_HOST:-host.docker.internal}
      - export ANDROID_ADB_SERVER_PORT=${ANDROID_ADB_SERVER_PORT:-5037}
      # VM Service用トンネル設定（ホットリロードのために必要）
      - adb -H host.docker.internal -P 5037 reverse tcp:8181 tcp:8181
      # アプリ実行（VM Serviceポート固定でホットリロード有効化）
      - flutter run -d emulator-5554 --host-vmservice-port=8181 --device-vmservice-port=8181 --disable-service-auth-codes

  flutter:devices:
    desc: 接続デバイス確認
    cmds:
      - export ANDROID_ADB_SERVER_HOST=${ANDROID_ADB_SERVER_HOST:-host.docker.internal}
      - export ANDROID_ADB_SERVER_PORT=${ANDROID_ADB_SERVER_PORT:-5037}
      - adb -H $ANDROID_ADB_SERVER_HOST -P $ANDROID_ADB_SERVER_PORT devices
      - cd app
      - flutter devices

  flutter:run-device:
    desc: 特定デバイスで実行
    cmds:
      - cd app
      - export ANDROID_ADB_SERVER_HOST=${ANDROID_ADB_SERVER_HOST:-host.docker.internal}
      - export ANDROID_ADB_SERVER_PORT=${ANDROID_ADB_SERVER_PORT:-5037}
      - flutter run -d {{.CLI_ARGS}}

  env:setup:
    desc: 環境変数恒久設定
    cmds:
      - echo 'export ANDROID_ADB_SERVER_HOST=host.docker.internal' >> ~/.bashrc
      - echo 'export ANDROID_ADB_SERVER_PORT=5037' >> ~/.bashrc
      - source ~/.bashrc

  build:
    desc: APKビルド
    cmds:
      - cd app
      - flutter build apk --debug

  install:
    desc: エミュレーターにアプリをインストール
    cmds:
      - adb -H host.docker.internal -P 5037 install -r app/build/app/outputs/flutter-apk/app-debug.apk

  start:
    desc: エミュレーターでアプリを起動
    cmds:
      - adb -H host.docker.internal -P 5037 shell am start -n com.example.behindapp/com.example.behindapp.MainActivity

  build-install-start:
    desc: ビルド→インストール→起動を一括実行
    cmds:
      - task: build
      - task: install
      - task: start

  flutter:doctor:
    desc: Flutter環境診断
    cmds:
      - cd app
      - flutter doctor

  flutter:clean:
    desc: Flutterプロジェクトクリーン
    cmds:
      - cd app
      - flutter clean

  flutter:pub-get:
    desc: 依存関係インストール
    cmds:
      - cd app
      - flutter pub get

  flutter:pub-upgrade:
    desc: 依存関係アップグレード
    cmds:
      - cd app
      - flutter pub upgrade

  flutter:analyze:
    desc: コード解析
    cmds:
      - cd app
      - flutter analyze

  flutter:test:
    desc: テスト実行
    cmds:
      - cd app
      - flutter test

  flutter:emulators:
    desc: エミュレーター一覧表示
    cmds:
      - cd app
      - flutter emulators

  adb:devices:
    desc: ADBデバイス一覧
    cmds:
      - adb -H host.docker.internal -P 5037 devices

  adb:shell:
    desc: ADBシェル接続
    cmds:
      - adb -H host.docker.internal -P 5037 shell

  adb:logcat:
    desc: ログ表示
    cmds:
      - adb -H host.docker.internal -P 5037 logcat

  adb:uninstall:
    desc: アプリアンインストール
    cmds:
      - adb -H host.docker.internal -P 5037 uninstall com.example.behindapp

  setup:check:
    desc: 環境設定確認
    cmds:
      - echo "=== 環境変数確認 ==="
      - echo "ANDROID_ADB_SERVER_HOST:"
      - echo "ANDROID_ADB_SERVER_PORT:"
      - echo ""
      - echo "=== ADB接続確認 ==="
      - adb -H host.docker.internal -P 5037 devices
      - echo ""
      - echo "=== Flutterデバイス確認 ==="
      - cd app
      - flutter devices

  setup:init:
    desc: 初期設定実行
    cmds:
      - task: env:setup
      - echo "環境変数設定完了"
      - echo "新しいターミナルを開いてください"

  help:
    desc: ヘルプ表示
    cmds:
      - echo "=== Flutter開発タスク ==="
      - echo "  task dev                    - エミュレーターでアプリ実行"
      - echo "  task build-install-start    - ビルド→インストール→起動"
      - echo "  task flutter:devices        - 接続デバイス確認"
      - echo "  task flutter:run-device     - 特定デバイスで実行"
      - echo ""
      - echo "=== ビルド・デプロイ ==="
      - echo "  task build                  - APKビルド"
      - echo "  task install                - エミュレーターにインストール"
      - echo "  task start                  - アプリ起動"
      - echo ""
      - echo "=== Flutterコマンド ==="
      - echo "  task flutter:doctor         - Flutter環境診断"
      - echo "  task flutter:clean          - プロジェクトクリーン"
      - echo "  task flutter:pub-get        - 依存関係インストール"
      - echo "  task flutter:analyze        - コード解析"
      - echo "  task flutter:test           - テスト実行"
      - echo ""
      - echo "=== ADBコマンド ==="
      - echo "  task adb:devices            - ADBデバイス一覧"
      - echo "  task adb:shell              - ADBシェル接続"
      - echo "  task adb:logcat             - ログ表示"
      - echo "  task adb:uninstall          - アプリアンインストール"
      - echo ""
      - echo "=== 設定 ==="
      - echo "  task setup:check            - 環境設定確認"
      - echo "  task setup:init             - 初期設定実行"
      - echo "  task env:setup              - 環境変数恒久設定"
      - echo ""
      - echo "=== ヘルプ ==="
      - echo "  task help                   - このヘルプを表示"
      - echo "  task -l                     - 全タスク一覧表示"
